[[pages]]
path = "streamlit_app.py"
name = "Interroger Observatoire"
icon = ":house:"

[[pages]]
path = "pages/creer_observatoire.py"
name = "Creer Observatoire"
icon = ":books:"

[[pages]]
path = "pages/nouvel_observatoire.py"
name = "Nouvel Observatoire"
icon = ":bar_chart:"
